### ISSUE TITLE
Not possible to choose NAV in organizations

### ISSUE THREAD

**Issue by tanvirchahal** [ViderumGlobal/ckanext-nav#6]
Not possible to choose NAV

**Comment by zelima** [comment]
Creation of CKAN organizations is a privilege of a sysadmin. While we could probably get the credentials for sysadmin and make changes, this I believe would not be the correct way to go. I assume clients on their end have somebody with sysadmin privileges and think that person is one who should create the organisation (which than will appear in dropdown)

**Comment by tanvirchahal** [comment]
fixed
